apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: garasu
  labels:
    app: garasu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: garasu
  template:
    metadata:
      labels:
        app: garasu
        video: dash
    spec:
      containers:
      - name: nginx-vts
        image: ugurcan377/nginx-vts
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "10m"
          limits:
            cpu: "250m"
      - name: vts-exporter
        image: sophos/nginx-vts-exporter
        ports:
        - containerPort: 9913

