kind: Service
apiVersion: v1
metadata:
  name: montest-service
  labels:
    app: montest
    k8s-app: montest
spec:
  selector:
    video: dash
  ports:
  - port: 9913
    targetPort: 9913
    name: vts-exporter
